services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:8000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main:create_app
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      bash -c "
        echo 'Waiting for MariaDB to become available...'
        until mysql -h db -u user -ppassword -e 'SELECT 1' &> /dev/null; do
          echo 'MariaDB not ready yet - sleeping for 1 second'
          sleep 1
        done
        echo 'MariaDB is ready!'
        
        # Initialize migrations directory if it doesn't exist
        if [ ! -d '/app/migrations' ]; then
          echo 'Initializing migrations directory...'
          flask db init
        fi
        
        # Run database migrations
        echo 'Running migrations...'
        flask db upgrade || true
        
        # Start the application
        echo 'Starting application...'
        flask run --host=0.0.0.0 --port=8000
      "

  db:
    image: mariadb:10.6
    env_file:
      - .env
    environment:
      - TZ=UTC
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: