# docker-compose.yml (Now at project root)
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: business-api-app
    ports:
      - "5555:8000" # Host:Container
    env_file:
      - .env # Load environment variables from .env file in the project root
    environment:
      - FLASK_ENV=development
    volumes:
      # Mounts the project root to /app in container
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: gunicorn --bind 0.0.0.0:8000 --workers 1 --reload "main:create_app()"
