"""initial_schema

Revision ID: 5847bc308102
Revises: 
Create Date: 2025-05-12 17:24:45.881129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5847bc308102'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_currencies_user_id', table_name='user_currencies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_currencies_user_id', 'user_currencies', ['user_id'], unique=False)
    # ### end Alembic commands ###
